### ISSUE TITLE
what does Y represent in your deepDTA toy data?

### ISSUE THREAD

**Issue by HiPracheta** [hkmztrk/DeepDTA#10]
Hi, what does Y represent in your deepDTA toy data? I need to replicate data for my own purpose . So I need to know how many columns and rows are there? Can you give a brief description of the dataset you used for the toy data?

**Comment by hkmztrk** [comment]
@HiPracheta, it depends on your data (how many drugs and proteins your dataset contains).  You can [refer ](https://github.com/hkmztrk/DeepDTA/blob/master/deepdta-toy/README.md) here for more information.

**Comment by HiPracheta** [comment]
The Y which u want us to download for training, does that also represent binding affinity?
I opened it in sublime text , looks like each line is something like this :
8004 9507 c0ad 0700 0000 008c 156e 756d

does each value represent binding affinity?

**Comment by hkmztrk** [comment]
Y of training data stores binding affinity but is in pickle format, so the values you see are byte forms.
