### ISSUE TITLE
setting up number of training for experiments

### ISSUE THREAD

**Issue by HiPracheta** [hkmztrk/DeepDTA#11]
Hi @Running Z @hkmztrk  how do u set the number of trainings for the experiments?
Can you provide me a code snippet?

**Comment by hkmztrk** [comment]
Do you mean number of epochs?

**Comment by HiPracheta** [comment]
No for testing I am setting the number of epochs as 1, still my code runs forever. is there some way to stop that?

**Comment by NithinChintala** [comment]
Hey @hkmztrk I'm trying to run the DTC and mytest data for testing, but it appears that there are some files missing.  How should certain files like test_fold_setting, ligands_can, and other files that are in the original paper's data folder, but are not in this new folder be obtained?.

**Comment by hkmztrk** [comment]
Are you running the toy-example or your own data?

**Comment by HiPracheta** [comment]
Hi, I am running on deepdta->source folder. is there someway that we can control the training? I mean like limit the number of iterations in the training? Right now, I think your code is set uup in such a way that if the val_loss becomes constant training stops. Let's say this happens after 1000 steps. (I'm not talking about epoch). Is it possible to limit the training in 10 iterations for example?

**Comment by hkmztrk** [comment]
@HiPracheta sorry it seems I somehow missed answering this. Maybe you already solved your issue. I

 later on added early stopping to the main code - just to give an idea (original paper just runs for 100 epochs)

https://github.com/hkmztrk/DeepDTA/blob/62b157ccd17b3fa2caa0aa1355f5a11c385c43b9/source/run_experiments.py#L362

Good luck.

**Comment by xuzhang5788** [comment]
How long will it take for training? When I ran run_experiments.py at DeepDTA/source/, it took almost 24 hours using one GPU and showed 
/home/pharma1/venv_silico/lib/python3.5/site-packages/matplotlib/pyplot.py:522: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)
and then stopped. I am not sure if it is normal stop or not. 

I couldn't find the saved model.  Do I need to retrain the model using the best hyperparameters and then do the prediction? Thanks.

**Comment by hkmztrk** [comment]
hello @xuzhang5788, I added `plt.close()` line so that should fix the warning for figures.

As for training time it depends on the size of your data and the number of values you want to test for different parameters. I wish to add a model save line soon.
