### ISSUE TITLE
About Confidence and interval and p value

### ISSUE THREAD

**Issue by Gvinkc** [hkmztrk/DeepDTA#12]
Could you please let us know how did you calculate the Confidence interval and p-value? I did not see the codes for this calculation. I would appreciate if you could upload them. 
Thank you very much.

**Comment by hkmztrk** [comment]
Hello @Gvinkc, we performed statistical tests using a seperate tool once we obtained the results from DeepDTA. You can use a tool of your choice (e.g. in R, Python or simply an online tool) to perform the statistical analysis.

**Comment by Gvinkc** [comment]
Thank you :)
