### ISSUE TITLE
bestparamind is not defined in run_experiments.py

### ISSUE THREAD

**Issue by sathyapatel** [hkmztrk/DeepDTA#14]
File "run_experiments.py", line 256, in nfold_1_2_3_setting_sample
    testperf = all_predictions[bestparamind]##pointer pos 
TypeError: bestparamind is not defined

**Comment by hkmztrk** [comment]
@sathyapatel should work now. Could you check it?

**Comment by sathyapatel** [comment]
yes, it works fine now..Thanks for the fix
