### ISSUE TITLE
Adding prediction code?

### ISSUE THREAD

**Issue by zhouhao-learning** [hkmztrk/DeepDTA#15]
Hello, are you considering adding a prediction code script? For example, after I have trained the model, I want to use the trained model to predict the affinity of molecules and proteins. I have smiles files of molecules and sequence files of proteins. I can run the prediction script directly, get the prediction results, and save the prediction results as files.

**Comment by hkmztrk** [comment]
@zhouhao-learning this might help you,

https://github.com/hkmztrk/DeepDTA/tree/master/deepdta-toy
