### ISSUE TITLE
Filter length

### ISSUE THREAD

**Issue by garcia-nacho** [hkmztrk/DeepDTA#16]
https://github.com/hkmztrk/DeepDTA/blob/a3405c60c4f5d6d509c914c9c6444906cd3caca6/deepdta-toy/run_experiments.py#L75

https://github.com/hkmztrk/DeepDTA/blob/a3405c60c4f5d6d509c914c9c6444906cd3caca6/deepdta-toy/run_experiments.py#L76

In lines 75 and 76 it says FILTER_LENGTH1. Should it say FILTER_LENGTH2?

Awesome work and repository BTW

**Comment by hkmztrk** [comment]
Hello @garcia-nacho, thanks a lot for your interest in DeepDTA!

You are right, they should be FILTER_LENGTH2. DeepDTA actually uses label/categorical encoding - so i just included onehot version later in case people wanted to use. I'll update them, thanks.
