### ISSUE TITLE
arguments.py err

### ISSUE THREAD

**Issue by cgh2797** [hkmztrk/DeepDTA#19]
in arguments.py,
type of "--seq_window_lengths", "--smi_window_lengths","--num_windows" are "int"
(Also, I don't know what to assign value for these three.)

but, at "general_nfold_cv" in "run_exeperiments.py"
The code looks like this:
len(paramser1)*len(paramser2)*len(paramser3)

but! int has no len() !!
what should I do?

also , another ploblem.
in general_nfold_cv

this is may be error...
param1value = paramset1[param1ind]
 param2value = paramset2[param2ind]
  param3value = paramset3[param3ind]

**Comment by hkmztrk** [comment]
Hello @cgh2797, 

As in the example below,
```
  parser.add_argument(
      '--seq_window_lengths',
      type=int,
      nargs='+',
      help='Space seperated list of motif filter lengths. (ex, --window_lengths 4 8 12)'
  )
```
`nargs` argument brings in the functionality of 'number of arguments' - meaning that it allows you to pass more than one value and thus treats it like a list. in case of `+` it means we can pass at least one or more values. 

As for your other question of what values to assign these arguments "--seq_window_lengths", "--smi_window_lengths","--num_windows", you can start with the recommended ones in DeepDTA paper or simply experiment with different value ranges. 

Good luck.

**Comment by cgh2797** [comment]
w
