### ISSUE TITLE
error message when I ran /DeepDTA/deepdta-toy/run_experiments.py

### ISSUE THREAD

**Issue by xuzhang5788** [hkmztrk/DeepDTA#21]
I got the following error message:

File "run_experiments.py", line 548, in <module>
    os.makedirs(FLAGS.log_dir)
  File "/home/pharma1/venv_silico/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/tmp1588488527.3336222/'

Please help me. Many thanks

**Comment by hkmztrk** [comment]
Hello @xuzhang5788, one reason might be because you previously ran the code with sudo.

**Comment by xuzhang5788** [comment]
Thank you for your fast reply.
No, I didn't run it with sudo. I ran it at the virtual environment in which I ran your code at DeepDTA/source/ without any problems.

**Comment by hkmztrk** [comment]
Hi @xuzhang5788, as above is the only time I faced this issue I have no other suggestions unfortunately. How about trying these solutions? [one](https://stackoverflow.com/questions/23870808/oserror-errno-13-permission-denied) [two](https://stackoverflow.com/questions/32329976/makedirs-gives-oserror-errno-13-permission-denied-pdf-files) [three](https://stackoverflow.com/questions/13207450/permissionerror-errno-13-in-python)

**Comment by xuzhang5788** [comment]
@hkmztrk Thank you.

I restart the terminal, it worked. However, it ran with CPU, not GPU. I don't know why.

**Comment by xuzhang5788** [comment]
@hkmztrk 
I have to restart the machine to use GPU, otherwise the GPU memory wasn't released. I don't know if you could add some lines in you .py file to release GPU.

**Comment by xuzhang5788** [comment]
I used:
python run_experiments.py --num_windows 32 \
                          --seq_window_lengths 8 12 \
                          --smi_window_lengths 4 8 \
                          --batch_size 256 \
                          --num_epoch 100 \
                          --max_seq_len 1000 \
                          --max_smi_len 100 \
                          --train_path 'data/DTC/' \
                          --test_path 'data/mytest/' \
                          --problem_type 1 \
                          --isLog 0 \
                          --log_dir 'logs/'

and finished running without any errors in about 2 hours.

But the log file showed:

Namespace(batch_size=256, binary_th=0.0, checkpoint_path='', isLog=0, learning_rate=0.001, log_dir='logs/1588543837.272291/', max_seq_len=1000, max_smi_len=100, num_classes=0, num_epoch=100, num_hidden=0, num_windows=[32], problem_type=1, seq_window_lengths=[8, 12], smi_window_lengths=[4, 8], test_path='data/mytest/', train_path='data/DTC/')
---Parameter Search-----
P1 = 0,  P2 = 0, P3 = 0,  CI-i = 0.000000, CI-ii = 0.000000, MSE = 69.223587
P1 = 0,  P2 = 0, P3 = 1,  CI-i = 0.000000, CI-ii = 0.000000, MSE = 45.228275
P1 = 0,  P2 = 1, P3 = 0,  CI-i = 0.000000, CI-ii = 0.000000, MSE = 60.011765
P1 = 0,  P2 = 1, P3 = 1,  CI-i = 0.000000, CI-ii = 0.000000, MSE = 74.286850
---FINAL RESULTS-----
best param index = 0
Test Performance CI
[0]
Test Performance MSE
[69.22358703613281]
Setting 1
avg_perf = 0.00000,  avg_mse = 69.22359, std = 0.00000

It looks weird some how.

**Comment by hkmztrk** [comment]
Hello @xuzhang5788,

if tensorflow-gpu is installed in your machine, then the code automatically runs on GPU. I think somehow you are able to access GPU via sudo - hence the previous error with permission error.

it is expected that toy example yield to a poor performance since I made up an example binding affinity data just for the purpose of illustration and we don't know the true labels. You can replace these example files with your own data.

**Comment by xuzhang5788** [comment]
@hkmztrk 
Thank you so much. I will try later.
