### ISSUE TITLE
Running "S-W and Pubchem-Sim" case from DeepDTA 

### ISSUE THREAD

**Issue by SAkbari93** [hkmztrk/DeepDTA#27]
At first thanks for your interesting work and framework. I run its CNN-CNN case and it's constructive for me. Now I want to run S-W and Pubchem-Sim case instead of CNN-CNN case. for this purpose I replace build_baseline function in run_regression function and run the code but I receive untrackable errors. Maybe the required data for this is not in your default database? or other settings (like TensorFlow version and etc.) that I must observe in my run? I ran code in google colab. Could I have your advice on this?

**Comment by SAkbari93** [comment]
> At first thanks for your interesting work and framework. I run its CNN-CNN case and it's constructive for me. Now I want to run S-W and Pubchem-Sim case instead of CNN-CNN case. for this purpose I replace build_baseline function in run_regression function and run the code but I receive untrackable errors. Maybe the required data for this is not in your default database? or other settings (like TensorFlow version and etc.) that I must observe in my run? I ran code in google colab. Could I have your advice on this?

isn't required to set problem_type to another value to run  S-W and Pubchem-Sim? what does this parameter show?

**Comment by SAkbari93** [comment]
@

**Comment by hkmztrk** [comment]
Hi @SAkbari93, you can modify/use the example functions build_single_drug or build_single_prot functions if you want to run the model with S-W and Pubchem similarity matrices (the following files for corresponding datasets). 

kiba_drug_sim.txt
kiba_target_sim.txt

drug-drug_similarities_2D.txt
target-target_similarities_WS.txt

**Comment by SAkbari93** [comment]
> kiba_target_sim.txt

Hi @hkmztrk Thanks for your response.  I try to do this but I can't find lines that these files included in the code. can you help me to use them in the code? It seems there isn't a function to parse them, isn't?
