### ISSUE TITLE
MSE for davis dataset is very high than that is mentioned in the paper

### ISSUE THREAD

**Issue by ashu-jbnu** [hkmztrk/DeepDTA#30]
DeepDTA paper mentioned that the MSE for davis dataset is 0.261 but I did not find the value nearer when I run the code.

I cloned the DeepDTA code from github. Created the environment mentioned in the Readme.md file and then tried running the code. But the loss for davis dataset is very huge, though for KIBA the loss is as per expectations. Did I miss something while setting up the code? I have attached the screenshot of training in this comment.
![davis_issue](https://user-images.githubusercontent.com/94941204/158001705-8bb2f863-aa40-442c-8e8f-e2bb87fda72f.JPG)

**Comment by hkmztrk** [comment]
Hi @ashu-jbnu, for Davis dataset you need to set `is_log` argument to `1`

https://github.com/hkmztrk/DeepDTA/blob/2c9cbafdfb383f2f03bcea4b231b90a072e65b15/source/arguments.py#L92

**Comment by ashu-jbnu** [comment]
@hkmztrk  Thank you for your response. Now this has worked. But why is the is_log argument different for davis and kiba dataset? Does this mean that they(davis and kiba dataset) have different formula to calculate MSE?

**Comment by hkmztrk** [comment]
MSE calculation is the same - Davis dataset binding values are used after log transformation, please refer to the paper for more detail.

**Comment by kiki-win** [comment]
@ashu-jbnu Hi，are you running the code with cpu?
