### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by kiki-win** [hkmztrk/DeepDTA#31]
Hi!I have a few questions to ask:
1. After installing the required environment (where python=2.7)
I moved the data folder to the source folder and ran the code using the "bash go.sh" command. Because the KIBA data set is used in the go.sh file, I tried to reproduce the data set first (I don't know if I understand it correctly).
I ran on the server for 3 days and only ran 54 epoch. The results are as follows:
![image](https://user-images.githubusercontent.com/74908431/160273905-0839f4f4-ee6f-4402-beef-f65bda0255a7.png)
![image](https://user-images.githubusercontent.com/74908431/160273914-630c4025-80e2-4d7c-b7dc-dda1adf9e59d.png)
![image](https://user-images.githubusercontent.com/74908431/160273888-d6bc8e6b-346e-4529-900d-bf111e11497f.png)
Is this running speed normal?
Are the obtained parameters close to your results?

2. If I want to reproduce Davis dataset, I need to change the default=0 of the arguments.py file to default=1. Is it right?

I have just come into contact with this field and am very interested in your code. I want to reproduce your code and hope to receive your reply. Thank you.

**Comment by hkmztrk** [comment]
Hi @kiki-win,

if you have GPU access then it'd be much faster, max 8-10 hours - you need to make sure you have tensorflow-gpu installed in that case. 

For davis dataset, you need to change `dataset_path` and `is_log` arguments while running the code. you don't need to modify the arguments.py file itself.
