### ISSUE TITLE
Could the pre-trained model be made available?

### ISSUE THREAD

**Issue by cwognum** [hkmztrk/DeepDTA#32]
Hi @hkmztrk, 

Congratulations on DeepDTA! I really enjoyed going through the work. I was wondering whether you would be be willing to share the weights of the models you trained in the process. I am building some DTI models myself and would like to benchmark against your results.

**Comment by hkmztrk** [comment]
Hi @cwognum, thanks a lot for your interest in deepdta! Unfortunately, I don't have the saved weights - it might be best to re-train it. I would be happy to help if you came across any issue doing so.

**Comment by cwognum** [comment]
Thank you for the quick reply! I will give it a go and will let you know if I run into any issues. :slightly_smiling_face:
