### ISSUE TITLE
Help with retraining the combined model with a different dataset

### ISSUE THREAD

**Issue by KSUN63** [hkmztrk/DeepDTA#33]
Hi there, 

I am interested in retraining your model with a different dataset, but I am having trouble downloading the right version of TensorFlow. I was able to create a conda environment with python 2.7, but I couldn't install any version of the TensorFlow via either pip or conda that is compatible with python 2.7 (they all require at least python 3.5). In this case, do you happen to have any suggestions to bypass this issue? (For you context, I am working with a windows machine)

Best,
Oliver

**Comment by hkmztrk** [comment]
Hi @KSUN63 thanks a lot for your interest in DeepDTA. The code in the repo uses versions indicated in README and also tested and works with Python 3.6, Tensorflow 1.15.0, Keras 2.1.6 in Linux. 

I would definitely advise using either the README versions or above specifications.

**Comment by KSUN63** [comment]
Thank you! I will try your suggested configuration and see if it works.
