### ISSUE TITLE
new datas

### ISSUE THREAD

**Issue by kiki-win** [hkmztrk/DeepDTA#34]
Hello, I have successfully run 'python run_experiments.py' on the server, how can I use your model to predict my data? For example, I have some compound smiles, protein sequences, and their IC50s. Looking forward to receiving your answer, thank you

**Comment by KSUN63** [comment]
Hi there, I am also trying to run deepdta for my own data and I would suggest you take a look at the folder deepdta-toy. In the readme file for that folder, it has some instructions on how to clean up your own data to feed into the model.

**Comment by kiki-win** [comment]
Thank you for your answer, and also, did you successfully reproduce the model? I ran 'run_experiments.py' but only got the following result, I didn't get the values of rm2 and mse, what is the reason? @KSUN63

**Comment by KSUN63** [comment]
What was your result? I think I had some plots generated but I think my server killed my job for some reason so it wasn't able to run till the very end.

**Comment by hkmztrk** [comment]
Hi, sorry somehow missed this!
 Did you resolve your issue @kiki-win? 
one of the main reasons server killing the job is usually a memory problem @KSUN63, I am assuming this has been resolved for you?

**Comment by kiki-win** [comment]
> 



> 嗨，对不起，不知何故错过了这个！你解决了你的问题吗？服务器终止作业的主要原因之一通常是内存问题，我假设这已经为您解决了？

Hello, my problem has not been solved. I ran the file "run_experiments.py", but I only got the result of CI. How can I get MSE and rm2?
![image](https://user-images.githubusercontent.com/74908431/233336476-4b93615e-2f0e-40d3-b328-157a724899ca.png)
This is the result of 100 epoch.

**Comment by hkmztrk** [comment]
Hi @kiki-win, during training we only monitor MSE loss and CI. Those large numbers are actually MSE. Which dataset are you testing?   For davis dataset, you need to set is_log=1, that should correct the MSE scale. 

Rm2 should be written in a separate file when training/testing ends.

**Comment by kiki-win** [comment]
What I am reproducing now is the Davis data set.
When you say' actually MSE', do you mean the 'val_loss value' in the picture?
Excuse me, how to set' is _ log = 1'?
Sorry, my programming foundation is poor, and I ask many questions. Thank you for your patience.

**Comment by hkmztrk** [comment]
No worries, yes, loss is the MSE, both for validation and training. 

To  set' is_log = 1', you have to run the code with the updated argument as below:

```
python run_experiments.py --num_windows 32 \
                          --seq_window_lengths 8 12 \
                          --smi_window_lengths 4 8 \
                          --batch_size 256 \
                          --num_epoch 100 \
                          --max_seq_len 1000 \
                          --max_smi_len 100 \
                          --dataset_path 'data/kiba/' \
                          --problem_type 1 \
                          --isLog 1 \
                          --log_dir 'logs/'
```
