### ISSUE TITLE
Question about implementation

### ISSUE THREAD

**Issue by hanulpark98** [hkmztrk/DeepDTA#39]
hi i have attempted to try and study the code and thanks for your effort
this may be a silly question but 
in the file "run_experiments.py" i found that in line 535,536 there weren't any parameters for get_cindex and build_combined_categorical, but in the file "emetrics.py" the function get_cindex(Y, P) requires Y and P and build_combined_categorical requires 4. 
do i have to fill it up myself? in case can you explain Y and P for me?

**Comment by hkmztrk** [comment]
Hi @hanulpark98, no worries :)

Those lines you refer to are, you can think of as placeholder variables for selected function, meaning 
https://github.com/hkmztrk/DeepDTA/blob/2c9cbafdfb383f2f03bcea4b231b90a072e65b15/source/run_experiments.py#L530

`perfmeasure` variable can take any function as long as these functions have the same inputs which is `Y` and `P`. If you recursively follow the functions where  `perfmeasure` is sent as argument you will reach to below line.  

https://github.com/hkmztrk/DeepDTA/blob/2c9cbafdfb383f2f03bcea4b231b90a072e65b15/source/run_experiments.py#L369

The code is a little bit old now but idea is to give it a little more flexibility whether you choose `get_cindex` or `get_aupr` functions from `emetrics.py`. Hope this makes sense.

You can refer to [here](https://github.com/hkmztrk/DeepDTA/issues/35) for pytorch implementation.

**Comment by hanulpark98** [comment]
oh that makes sense 
big thanks for the comment

**Comment by hanulpark98** [comment]
hi i've been studying your code since and found out that 11902 proteins * 1353 ligands binding affinity data of your dataset Y, there were only 50181 (which is 0.3 percent of the data) that were not NAN. can you explain how it is possible to train the data with so much missing data?

**Comment by hanulpark98** [comment]
> Hi @hanulpark98, no worries :)
> 
> Those lines you refer to are, you can think of as placeholder variables for selected function, meaning
> 
> https://github.com/hkmztrk/DeepDTA/blob/2c9cbafdfb383f2f03bcea4b231b90a072e65b15/source/run_experiments.py#L530
> 
> `perfmeasure` variable can take any function as long as these functions have the same inputs which is `Y` and `P`. If you recursively follow the functions where `perfmeasure` is sent as argument you will reach to below line.
> 
> https://github.com/hkmztrk/DeepDTA/blob/2c9cbafdfb383f2f03bcea4b231b90a072e65b15/source/run_experiments.py#L369
> 
> The code is a little bit old now but idea is to give it a little more flexibility whether you choose `get_cindex` or `get_aupr` functions from `emetrics.py`. Hope this makes sense.
> 
> You can refer to [here](https://github.com/hkmztrk/DeepDTA/issues/35) for pytorch implementation.

hi i've been studying your code since and found out that 11902 proteins * 1353 ligands binding affinity data of your dataset Y, there were only 50181 (which is 0.3 percent of the data) that were not NAN. can you explain how it is possible to train the data with so much missing data?

**Comment by hkmztrk** [comment]
Hi @hanulpark98, it is true that actual experimental data is quite limited and this eventually is an imbalanced dataset. Therefore, one can pay attention to metrics such as AUPR to interpret the results more carefully. Hope this answers your question. I'm closing the issue but feel free to comment/reopen.
