### ISSUE TITLE
A question about Davis dataset

### ISSUE THREAD

**Issue by realwangjiahao** [hkmztrk/DeepDTA#44]
Hello!
In your article 'DeepDTA: Deep Drug-Target Binding Affinity Prediction', you explained the two dataset: Davis and KIBA, and that's a good summary.
But I have a qusetion that in Davis dataset, you say there is 68 drugs, but the original dataset said they have 72 drug. I am wondering why,could you tell me?

**Comment by hkmztrk** [comment]
Hi @realwangjiahao, we used the datasets provided by Pahikkala et al. as it is, please [see here for details ](https://github.com/hkmztrk/DeepDTA/blob/master/data/README.md)
