### ISSUE TITLE
How to modify the code to calculate rm2?

### ISSUE THREAD

**Issue by a253324** [hkmztrk/DeepDTA#48]
I want the rm2 could be calculated when I run /source/run_experiments.py, but I met the error when I modified the code as follows：
![image](https://github.com/user-attachments/assets/24853809-fdbb-4d3d-ab4f-7c0fef47486f)
in line 530, where it should be the perfmeasure=get_cindex, I modified it to perfmeasure=get_rm2, which is suplied in the emetrics.py, but the erros happened:
![image](https://github.com/user-attachments/assets/22c2f48f-a583-42d6-97fc-df373e43fea4)

How to correct the code? Thanks!

**Comment by hkmztrk** [comment]
Hi @a253324, can you print out `y_obs` and `y_pred` so that I can try to re-create it? 
https://github.com/hkmztrk/DeepDTA/blob/a546a8433a6822e958f36171c4356ad6f414d623/source/emetrics.py#L43C4-L43C35

**Comment by a253324** [comment]
Thank you for your reply!@hkmztrk 
I print the value and shape of y_obs and y_pred respectively, the below is the print result:
![image](https://github.com/user-attachments/assets/325c82a5-b0a2-4109-b46d-8f1085817a38)
And the below is the error information:
![image](https://github.com/user-attachments/assets/23e0bbb7-8075-4e18-9dd4-863e1e416a8a)

The dataset is davis dataset. Thanks for your help!

**Comment by hkmztrk** [comment]
Hi @a253324 , could you check whether   adding y_pred = y_pred.flatten() before this line solves your issue? https://github.com/hkmztrk/DeepDTA/blob/a546a8433a6822e958f36171c4356ad6f414d623/deepdta-toy/run_experiments.py#L362

**Comment by a253324** [comment]
> Hi @a253324 , could you check whether adding y_pred = y_pred.flatten() before this line solves your issue?
> 
> https://github.com/hkmztrk/DeepDTA/blob/a546a8433a6822e958f36171c4356ad6f414d623/deepdta-toy/run_experiments.py#L362

Hi @hkmztrk , thank you for your reply. I added the y_pred = y_pred.flatten(), and the code run successfully. Thank you for your help!
