### ISSUE TITLE
TypeError: read_sets() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by lorenzoFabbri** [hkmztrk/DeepDTA#6]
I'm trying to run your code, but I encounter the following error:

```
Traceback (most recent call last):
  File "run_experiments.py", line 547, in <module>
    run_regression( FLAGS )
  File "run_experiments.py", line 534, in run_regression
    experiment(FLAGS, perfmeasure, deepmethod)
  File "run_experiments.py", line 494, in experiment
    need_shuffle = False )
  File "/Users/lorenzo/Downloads/DeepDTA/source/datahelper.py", line 122, in __init__
    self._raw = self.read_sets( fpath, setting_no )
TypeError: read_sets() takes 2 positional arguments but 3 were given
```

I saw you updated the repository a few days ago. Did you try running it with this changes? Thank you.

**Comment by hkmztrk** [comment]
Hi Lorenzo,

You are quite right, I realized I missed that part in update and fixed it just now. 
Could you try it again?

Thanks!

**Comment by lorenzoFabbri** [comment]
That problem seems to be solved, but the `self._raw` is commented so it cannot assign it to `self._num_data`.

**Comment by hkmztrk** [comment]
right, i commented out that too, because the code actually do not use those
