### ISSUE TITLE
DeepDTA: deep drug–target binding affinity prediction

### ISSUE THREAD

**Issue by huiwenwangjn** [hkmztrk/DeepDTA#8]
Hello, if I have the sequences of a given protein and the smiles of a given drug, how can I use your DeepDTA program to predict the drug–target binding affinity? Look forward to your reply.

**Comment by hkmztrk** [comment]
Hello @huiwenwangjn, thanks for your interest in our work!

Do you wish to train & test on your own dataset or you simply want binding affinity values for your data that will predict from a pre-trained model?

Best

**Comment by huiwenwangjn** [comment]
Hello,   Hakime Öztürk. Thank you for your reply. I simply want the binding affinity values for my data that will predict from a pre-trained DeepDTA model?

I am looking forward to your reply. With best wishes.


 
------------------ Original ------------------

**Comment by hkmztrk** [comment]
@huiwenwangjn, that's a nice suggestion then. I haven't implemented such module, but I can update the repo in a few days. In the meantime, could you tell me in  what format your data is? (txt, json, excel)

**Comment by huiwenwangjn** [comment]
Hello,   Hakime Öztürk. Thank  you for your reply and help again. There are the sequences of target proteins that were  saved in the targets.txt file, and the smiles of drugs corresponding to target proteins that were saved in the drugs.xlsx file (attachments). 

I am looking forward to your reply. With best wishes. 



Huiwen Wang

 
------------------ Original ------------------

**Comment by hkmztrk** [comment]
Hello @huiwenwangjn, I finally found a time to work on your update. Is it possible for you to send your inputs (or a part of inputs) so that I know how data is organized?

**Comment by huiwenwangjn** [comment]
Hello, Hakime Öztürk. Thank you for your reply and help again. There are my inputs including the sequences of  five proteins (1A30, 1EBY, 1GPK, 1GPN, 1E66) that were  saved in the targets.txt file (attachments), and the smiles of five drugs (5-mer, THK, THA, E12, HI6) corresponding to the five proteins (1A30, 1EBY, 1GPK, 1GPN, 1E66)  that were saved in the drugs.xlsx file (attachments). I simply want binding affinity values of five drug/protein pairs (5-mer/1A30, THK/1EBY, THA/1GPK, E12/1GPN, and HI6/1E66) that will predict from a pre-trained model.


I am looking forward to your reply. With best wishes. 



Huiwen Wang

 
 
------------------ Original ------------------

**Comment by hkmztrk** [comment]
@huiwenwangjn I started working on it, but it will take a few days. thanks a lot for your patience.

**Comment by huiwenwangjn** [comment]
Hello, Hakime Öztürk. Thank you for your help. With best wishes. 
 
 
------------------ Original ------------------

**Comment by hkmztrk** [comment]
Hello @huiwenwangjn , sorry for late response. 
I included a new folder here, https://github.com/hkmztrk/DeepDTA/tree/master/deepdta-toy

Please feel free to ask if you need further instructions or face any issues while running.

**Comment by huiwenwangjn** [comment]
Hello,  Hakime Öztürk. Thank you for all the help you have given me. I especially appreciate the program you have provided.  
Again, thank you so much. With best wishes.  
Huiwen Wang
 
 
------------------ Original ------------------
From: "hkmztrk"; 
Date: 2019年7月4日(星期四) 凌晨2:42
To: "hkmztrk/DeepDTA"; 
Cc: "huiwenwangjn"; "Mention"; 
Subject: Re: [hkmztrk/DeepDTA] DeepDTA: deep drug–target binding affinity prediction (#8)

 

Hello @huiwenwangjn , sorry for late response.
 I included a new folder here, https://github.com/hkmztrk/DeepDTA/tree/master/deepdta-toy
 
Please feel free to ask if you need further instructions or face any issues while running.

**Comment by cgh2797** [comment]
@hkmztrk  why you use DTC data at DeepDTA-toy?? 
hmm... because DTC is better than KIBA and DAVIS??

**Comment by hkmztrk** [comment]
@cgh2797 not better, but a larger a dataset, plus I wanted to provide some variety to existing datasets for people that are interested.
